import { Book } from "@shared/schema";

export const mockBooks: Book[] = [
  {
    id: 1,
    title: "Dune",
    author: "Frank Herbert",
    synopsis: "Set in the distant future amidst a feudal interstellar society in which noble houses, in control of individual planets, owe allegiance to the Padishah Emperor, Dune tells the story of young Paul Atreides, whose family accepts the stewardship of the planet Arrakis.",
    genre: "Science Fiction",
    coverImageUrl: "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=600",
    trailerVideoUrl: "https://www.youtube.com/embed/n9xhJrPXop4",
    amazonPurchaseUrl: "https://amazon.com/dp/0441172717",
    movieWatchUrl: "https://www.hbo.com/movies/dune",
    rating: 4.5,
    reviewCount: 12345,
    isPublished: true,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    synopsis: "Pride and Prejudice follows the turbulent relationship between Elizabeth Bennet, the daughter of a country gentleman, and Fitzwilliam Darcy, a rich aristocratic landowner.",
    genre: "Romance",
    coverImageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=600",
    trailerVideoUrl: "https://www.youtube.com/embed/1dYv5u6v55Y",
    amazonPurchaseUrl: "https://amazon.com/dp/0141439513",
    movieWatchUrl: "https://www.netflix.com/title/70023048",
    rating: 4.2,
    reviewCount: 8767,
    isPublished: true,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    title: "1984",
    author: "George Orwell",
    synopsis: "Winston Smith works for the Ministry of Truth in London, chief city of Airstrip One. Big Brother stares out from every poster, the Thought Police uncover every act of betrayal.",
    genre: "Dystopian",
    coverImageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=600",
    trailerVideoUrl: "https://www.youtube.com/embed/Z4rBDUJTnNU",
    amazonPurchaseUrl: "https://amazon.com/dp/0452284236",
    movieWatchUrl: "https://www.amazon.com/1984-John-Hurt/dp/B00AEBB1G8",
    rating: 4.8,
    reviewCount: 15234,
    isPublished: true,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    synopsis: "In a hole in the ground there lived a hobbit. Written for J.R.R. Tolkien's own children, The Hobbit met with instant critical acclaim when it was first published in 1937.",
    genre: "Fantasy",
    coverImageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=600",
    trailerVideoUrl: "https://www.youtube.com/embed/SDnYMbYB-nU",
    amazonPurchaseUrl: "https://amazon.com/dp/054792822X",
    movieWatchUrl: "https://www.hbo.com/movies/the-hobbit-trilogy",
    rating: 4.6,
    reviewCount: 11876,
    isPublished: true,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const genres = [
  "Fantasy",
  "Romance", 
  "Science Fiction",
  "Mystery",
  "Thriller",
  "Historical",
  "Dystopian",
];
